In [1]:
import pandas as pd
modality = pd.read_csv("lynott_connell_2009_modality.csv")
modality

PropertyBritish       Word DominantModality     Sight     Touch     Sound  \
0          abrasive   abrasive           Haptic  2.894737  3.684211  1.684211   
1         absorbent  absorbent           Visual  4.142857  3.142857  0.714286   
2            aching     aching           Haptic  2.047619  3.666667  0.666667   
3            acidic     acidic        Gustatory  2.190476  1.142857  0.476190   
4             acrid      acrid        Olfactory  1.125000  0.625000  0.375000   
..              ...        ...              ...       ...       ...       ...   
418            wiry       wiry           Visual  4.190476  4.095238  1.047619   
419           wispy      wispy           Visual  4.210526  3.263158  1.631579   
420         wizened    wizened           Visual  3.100000  0.800000  2.900000   
421          woolly     woolly           Haptic  4.285714  4.428571  0.142857   
422          yellow     yellow           Visual  4.900000  0.000000  0.150000   

        Taste     Smell  ModalityExclusivity  
0    0.578947  0.578947             0.329609  
1    0.476190  0.476190             0.409574  
2    0.047619  0.095238             0.554745  
3    4.190476  2.904762             0.340611  
4    3.000000  3.500000             0.362319  
..        ...       ...                  ...  
418  0.761905  0.285714             0.376147  
419  0.894737  0.263158             0.384615  
420  0.100000  0.300000             0.416667  
421  0.142857  0.142857             0.468750  
422  0.050000  0.050000             0.951456  

[423 rows x 9 columns]

In [2]:
iconicity = pd.read_csv("perry_winter_2017_iconicity.csv")
iconicity

Word          POS   SER  CorteseImag  Conc      Syst       Freq  \
0            a  Grammatical   NaN          NaN  1.46       NaN  1041179.0   
1        abide         Verb   NaN          NaN  1.68       NaN      138.0   
2         able    Adjective  1.73          NaN  2.38       NaN     8155.0   
3        about  Grammatical  1.20          NaN  1.77       NaN   185206.0   
4        above  Grammatical  2.91          NaN  3.33       NaN     2493.0   
...        ...          ...   ...          ...   ...       ...        ...   
2996  zippered         Verb   NaN          NaN  4.12       NaN        3.0   
2997      zone         Noun   NaN          4.1  3.07  0.000051     1026.0   
2998       zoo         Noun  3.40          6.8  4.81  0.000015      696.0   
2999      zoom         Verb  3.40          3.5  3.10  0.000022      181.0   
3000  zucchini         Noun   NaN          NaN  4.87       NaN       49.0   

      Iconicity  
0      0.461538  
1      0.250000  
2      0.466667  
3     -0.100000  
4      1.062500  
...         ...  
2996   1.583333  
2997  -0.100000  
2998   1.538462  
2999   3.600000  
3000   0.100000  

[3001 rows x 8 columns]

In [3]:
both = pd.merge(modality, iconicity, on="Word")[["Word", "DominantModality", "Iconicity"]]
both

Word DominantModality  Iconicity
0     abrasive           Haptic   1.312500
1    absorbent           Visual   0.923077
2       aching           Haptic   0.250000
3       acidic        Gustatory   1.000000
4        acrid        Olfactory   0.615385
..         ...              ...        ...
417       wiry           Visual   1.500000
418      wispy           Visual   2.571429
419    wizened           Visual  -0.846154
420     woolly           Haptic   2.000000
421     yellow           Visual   0.500000

[422 rows x 3 columns]

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

In [5]:
X_raw = both["DominantModality"].to_numpy()[:, None]

In [6]:
encoder = OneHotEncoder()
X = encoder.fit_transform(X_raw).A
X

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
model = LinearRegression(fit_intercept=False)
model.fit(X, both["Iconicity"])
model

LinearRegression(fit_intercept=False)

In [8]:
import numpy as np
np.unique(model.predict(X))

array([0.80555556, 1.01159247, 1.22314716, 1.81253473, 2.25610664])

In [9]:
model.coef_

array([2.25610664, 0.80555556, 1.81253473, 1.01159247, 1.22314716])

In [10]:
model.intercept_

0.0

In [11]:
model.coef_ + model.intercept_

array([2.25610664, 0.80555556, 1.81253473, 1.01159247, 1.22314716])

In [12]:
both["DominantModality"].value_counts()

Visual       204
Haptic        70
Auditory      68
Gustatory     54
Olfactory     26
Name: DominantModality, dtype: int64